---
#
# Prepare to bring up Devstack
#
- name: devstack | main | Update the apt-get cache
  apt: update_cache=yes
  become: yes

- name: devstack | main | Install python-apt for ansible
  apt: name=python-apt state=latest
  become: yes

- name: devstack | main | Install vim
  apt: name=vim state=latest
  become: yes

- name: devstack | main | Ensure git is up to date
  apt: name=git state=latest
  become: yes

#
# Devstack
#
- name: devstack | main | Clone the devstack repo
  git: repo=https://github.com/openstack-dev/devstack.git
       dest=/home/vagrant/devstack
       version="{{ branch }}"

- name: devstack | main | Generate the local.conf file
  template: src=templates/devstack.j2 dest=/home/vagrant/devstack/local.conf

- name: devstack | main | Run stack.sh to bring up devstack
  shell: cd /home/vagrant/devstack/ && /home/vagrant/devstack/stack.sh > /home/vagrant/devstack/stack.log
